### ISSUE TITLE
anmn_nrs_bgc harvester: iUpdateSpatialExtent component fails

### ISSUE THREAD

**Issue by dnahodil** [aodn/harvesters#119]
**Observed behaviour**
On running the harvester on 14-nsp-mel, the following error occurs:
> Exception in component iUpdateSpatialExtent_1 org.postgresql.util.PSQLException: ERROR: relation "indexed_file" does not exist

**Expected behaviour**
No exception!

**Comment by mhidas** [comment]
This has been fixed by adding the "always run" option to the iUpdateSpatialExtent component (https://github.com/aodn/talend-components/pull/32)
