### ISSUE TITLE
Could we use issue labels to keep track of harvesters in need of (re-)deployment?

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#183]
It seems like a bit of an inefficient process we go through every iteration: we email Seb or Bene a list of harvesters we want re-depoyed (if we remember them all), he takes it to JPSR, and eventually they make it into an iteration.

Since every change that requires (re-)deployment of a harvester will have a PR or issue ticket here, couldn't we just have a label like `to_be_deployed` (or `TBD`), which we could add whenever it is ready to be deployed.

Then, whoever deploys or updates the harvester would remove that tag and instead apply another one, like `in_RC` or `in_production` to indicate where it's been deployed. 

Any thoughts? @pblain @smancini

**Comment by pblain** [comment]
@mhidas, that sounds reasonable.  As of this iteration GG and Loz should be able to deploy harvesters - so you won't be subject to the scrum cycle in any case.

**Comment by mhidas** [comment]
Anyone else have any thoughts on this? If we agree it's worth doing, we'll need to get @pblain to create these labels. I don't seem to be able to.

**Comment by pblain** [comment]
Happy to add the labels if you guys want me too.

**Comment by mhidas** [comment]
Ok, I've managed to create the labels I mentioned above. 

@lbesnard @ggalibert @xhoenner @bpasquer When you merge a pull-request in this repo, add the `to_be_deployed` label. When they get deployed, remove that one and instead add `in_RC` or `in_production`.

You can see the harvesters waiting to be re-deployed using this link:
https://github.com/aodn/harvesters/pulls?q=is%3Apr+is%3Aclosed+label%3Ato_be_deployed

**Comment by lbesnard** [comment]
@mhidas :+1:  looks really good tome

**Comment by lbesnard** [comment]
FIY to recreate this link , click on 'to_be_deployed' in https://github.com/aodn/harvesters/labels   and then click on the word 'closed'

**Comment by lbesnard** [comment]
As discussed with @mhidas today, I think it would be actually better to open a new issue (with a link to the PR and the correct label) when a harvester needs to be redeploy to RC and prod. It's easier to find through Github, and in the case of many PR for one deployment, it's easier to understand the workflow in one page only.

**Comment by mhidas** [comment]
Yes, let's do that!
