### ISSUE TITLE
ABOS_SOFS_SURFACE_FLUXES - deployment

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#200]
in ref of https://github.com/aodn/harvesters/pull/199

**Comment by lbesnard** [comment]
new build is on RC. harvester is queued to run today. Please check log this eve or tomorrow @mhidas 
```
talend_log abos_sofs_fl-abos_sofs_fl
```

**Comment by mhidas** [comment]
Still failing:

    Caused by: java.lang.Error: Unresolved compilation problem: 
        fileId cannot be resolved or is not a field

        at abos_sofs_surface_fluxes.harvestsofsfile_0_1.HarvestSOFSFile.tPostgresqlRow_1Process(HarvestSOFSFile.java:701)
        at abos_sofs_surface_fluxes.harvestsofsfile_0_1.HarvestSOFSFile.tPostgresqlConnection_1Process(HarvestSOFSFile.java:627)

See #203  for fix.

**Comment by lbesnard** [comment]
A few things missing :
in harvestSOFSfile component in main :
 * missing intValue() for the fileId : ((Long)globalMap.get("iHarvestResources_1_FILE_ID")).intValue()
 * missing url parameter

in actual harvestSOFSfile component :
 * fileId was a string type. has to be integer
 * url context was missing
 * deploymentNo context was missing

Currently running on my machine to test that's all missing. Happy to push force the modification on this branch for you if you want me to

**Comment by mhidas** [comment]
Ah, thanks @lbesnard ! All this was there originally. I don't know why it disappeared. Sure, if you've already made these changes, might as well commit them.

**Comment by mhidas** [comment]
@lbesnard Ok, should be ready to redeploy now!

**Comment by lbesnard** [comment]
@jonescc 

Can you please have a look at the log file on nsp14 ?
```
/mnt/ebs/talend/jobs/abos_sofs_fl-abos_sofs_fl/log/console.2015-04-20-16-20-08.log
```
basically some ' it.geosolutions.geonetwork.exception.GNServerException: Error retrieving metadata in GeoNetwork' . However if I rerun the harvester, well 
```
* iUpdateSpatialExtent - files changed: false
* iUpdateSpatialExtent - updating spatial extent: false
* iUpdateSpatialExtent - files changed: false
* iUpdateSpatialExtent - updating spatial extent: false
```
which seems to me like since it failed on the previous run, but still did something, well it doens't have to do it again.

**Comment by lbesnard** [comment]
> basically some ' it.geosolutions.geonetwork.exception.GNServerException: Error retrieving metadata in GeoNetwork' . However if I rerun the harvester, well
> 
> * iUpdateSpatialExtent - files changed: false
> * iUpdateSpatialExtent - updating spatial extent: false
> * iUpdateSpatialExtent - files changed: false
> * iUpdateSpatialExtent - updating spatial extent: false

I guess this should get fixed by @danfruehauf 's changes https://github.com/aodn/chef-private/commit/f424ed703c99c435d0ad2880375247aa5b289469

**Comment by mhidas** [comment]
Looks like the changes in #203 are in prod now and working fine. Thanks for your persistence @lbesnard  !

**Comment by lbesnard** [comment]
no worries
