### ISSUE TITLE
talend_build

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#202]
as well as having talend_show talend_log, It would be great to add talend_build or talend_version (useful to quickly compare with jenkins) reading the jave/***.build file. 

something like ?

```bash
talend_version () 
{ 
    local talend_job=$1;
    shift;
    less /mnt/ebs/talend/jobs/$talend_job/java/build.properties
}
```

@danfruehauf  ?

**Comment by danfruehauf** [comment]
Yep, it would be very nice, I just never got around to do it...

**Comment by lbesnard** [comment]
done
https://github.com/aodn/chef/commit/5eee57ee2324dd1f687461ee0f7daa9948691609

**Comment by danfruehauf** [comment]
We usually link the PR, not the commit, so:
https://github.com/aodn/chef/pull/89
