### ISSUE TITLE
Update scheduled time for ABOS_SOFS harvesters

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#208]
Realtime data from the SOFS mooring are updated on opendap at 11:30am every day. Therefore it would make sense to run the harvesters for these data right after this time, i.e. at **11:35am**.

Harvesters to update:
ABOS_SOFS_SURFACE_PROPERTIES
ABOS_SOFS_SURFACE_FLUXES

@lbesnard or @ggalibert Could you please have a look at this when you get to it?

**Comment by lbesnard** [comment]
@danfruehauf I know you have some ideas about triggering the harvester with the event driven system, but do you know what can be done in the meantime to improve this ?

**Comment by danfruehauf** [comment]
You can trigger it at 11:35am if you want. However I highly discourage running harvesters during business hours (9-17).

**Comment by lbesnard** [comment]
@mhidas , this is done. Would probably be effective on Friday. Would be good though if you could make the harvester name consistent with schemas like abos_sofs_sp, abos_sofs_surfaceprop_rt_map, abos_sofs_surface_properties.
