### ISSUE TITLE
iNetCDFInput - issue with char

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#213]
## ISSUE - Example with Argo harvester

In subjob HarvestArgoProfile, in the profile_measurements schema from iNetcdfInput_1. If the QC variables are set up as __char, length 1__ instead of string, the values output for the QC variable will have its first value repeated N times (N = the dim of the variable).

Example, from ncdump
```bash
ncdump -v PRES_QC /mnt/opendap/1/IMOS/opendap/Argo/dac/coriolis/5902310/profiles/R5902310_014.nc

...
 PRES_QC =
  "44444111111111111111111111111111111111111111111111114111111111" ;
}

```

but querying the database, argo.profile_measurements, for this file, only the value 4 will be output.

It seems like there is an issue with how iNetcdfInput handles char ? @jonescc

**Comment by jonescc** [comment]
Looks like I made an assumption that an array of characters should be a string in the component so the last dimension of a character array is always turned into a string. This is sometimes useful, but shouldn't be the default!  Probably should look at whether the output is meant to be a string or a character and behave accordingly.

**Comment by lbesnard** [comment]
so do you mean there somehting I could do in the harvester, or it's more in the component ?

**Comment by jonescc** [comment]
There's some work to change the way the component is handling this - so should go onto the backlog.  This is how the problem should be resolved rather than PO's working around the problem in each harvester - so I'd like to think it could be prioritised up the list @pblain @dnahodil

**Comment by lbesnard** [comment]
should be fixed now. I'll close it in a few days once the harvester will have finished running on RC

**Comment by lbesnard** [comment]
@danfruehauf  please check with 
```sql
select * from argo.profile_download where url like '%5902310/profiles/R5902310_014.nc'
--- should contain "44444111111111111111111111111111111111111111111111114111111111" for pres qc and not just 4444444. 

-- you can also do this do see if the file has been processed yet
select * from argo.indexed_file where url like '%5902310/profiles/R5902310_014.nc';
```

if good yolo
