### ISSUE TITLE
ANMN_WAVE harvester indexing real-time files

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#249]
The indexed_file table in the anmn_wave schema includes many real-time files from FAIMMS. Looks like the harvester is ignoring them, i.e. they're not appearing in the layer, but they probably don't need to be there in the first place. The cause is a single wrong character in the exclude pattern: instead of `.*REAL-TIME.*\.nc`  it should be `.*REAL_TIME.*\.nc` (underscore instead of hyphen).

Not urgent to fix, just thought I'd log this while I see it.

**Comment by lbesnard** [comment]
Yeap, that's not really a bug. I wrote the harvester like this, to harvest all wave files from ANMN. I could not make the exclude work for some reason, so decided to go around this by doing a sql query filter to only deal with files containing AWAC or ADCP , done in the advanced tab of the iharvestressources component. 
It's working fine this way, but feel free to modify the harvester if you want.
