### ISSUE TITLE
ANMN_ACIDIFICATION_NRT: data from deleted files still in database

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#254]
Data from an older version of a real-time file (long since deleted) is still in the `anmn_acidification_nrt` schema in harvest. The Talend harvester is supposed to delete these when the indexing no longer finds the file, but somehow this one was missed. What this means is when I try to download data from the collection **ANMN Acidification Moorings (AM) Sub-Facility - Near-real-time raw data** (select Deployment Code: NRSMAI-CO2-1504 as filter), I get duplicate entries in the CSV, or a fail message when trying to include the non-existent netCDF in the download.

We noticed this a while ago, and I seem to remember @jonescc was going to fix something in one of the Talend components to avoid this happening again, but I don't remember any more. Any updates, Craig?

**Comment by lbesnard** [comment]
I also had a similar issue with AUV viewer track harvester

**Comment by mhidas** [comment]
@jonescc We still have duplicates in this schema (anmn_acidification_nrt) and I can't remove them manually. How can we fix it?

**Comment by jonescc** [comment]
@mhidas, yes there was a problem with the talend harvesters not picking up deleted files which was fixed in a talend component.  These changes were made a while back and all harvesters have been recompiled in rc and production with these changes.

However, looks to me like the problem file above occurred before the changes made it to production.   I can't see any other instances where this has occurred since then. 

Looks to me like we need a one-off cleanup for this problem file - ie a liquibase changeset to remove data created for it.

Probably the same problem/solution for @lbesnard

**Comment by jonescc** [comment]
Looks like @lbesnard has already cleaned up his data.

**Comment by jonescc** [comment]
You can identify problem files like this using a query like:

select * from timeseries where file_id not in (select file_id from file_harvest where last_change_type <> 'deleted');

Replacing timeseries with the feature instance table that is applicable.  Might be worth running this on other collections where files are regularly deleted.

**Comment by mhidas** [comment]
@jonescc Thanks. See PR #281 for the fix, including new unique constraints in the table to prevent this issue in the future (for this harvester at least).

**Comment by ggalibert** [comment]
Can we close this?

**Comment by mhidas** [comment]
@ggalibert  Not yet. The fix has been merged, but not yet deployed to prod. It is on RC and running ok.

Could you or @lbesnard please deploy it?

**Comment by mhidas** [comment]
@ggalibert @lbesnard The fix in #281 still hasn't been deployed on prod. Could  you please do it? Thanks.

**Comment by danfruehauf** [comment]
@mhidas I'll look into that.

**Comment by danfruehauf** [comment]
Had to rebuild it (due to jenkins discarding older builds), but now deploying both on RC and prod.

**Comment by mhidas** [comment]
Thanks @danfruehauf !
