### ISSUE TITLE
ABOS generic metadata harvester failing

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#259]
This is harvesting metadata for reporting, accessing the files via THREDDS. It is currently failing with an exception like this for every file:
```
2015-08-05T18:08:48000Z|GLOBAL ATTRIBUTE|HARVESTING FILE|4003|https://thredds.aodn.org.au/thredds/dodsC/IMOS/ABOS/ASFS/SOFS/Surface_waves/Real-time/2010_daily/IMOS_ABOS-ASFS_W_20100519T001500Z_SOFS_FV01_MRU.nc|2013-02-07T14:54:13000Z
Error on line 2 of document  : Element type "Datasetname" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "Datasetname" must be followed by either attribute specifications, ">" or "/>".
```

**Comment by mhidas** [comment]
This harvester needs some other changes. When I get to it, I could get it to read files directly from the filesystem instead of THREDDS.

**Comment by danfruehauf** [comment]
This is due to a bug in the new thredds that's providing malformed XML, see also:
https://github.com/Unidata/thredds/issues/150
