### ISSUE TITLE
ACORN radial is not up to date

### ISSUE THREAD

**Issue by ggalibert** [aodn/harvesters#266]
The latest radial files that have been listed in dbprod by the acorn radial non qc harvester are dated of 20 June.

There are obviously more recent files in opendap but the harvester didn't pick them up somehow. Also there is no trace of error in the talend logs.

**Comment by danfruehauf** [comment]
Ouch. Lets look into that ASAP.

**Comment by ggalibert** [comment]
Ok, looks like the last run on 15/08 has ran successfully and now dbprod is showing files dated 15/08 which is good!
