### ISSUE TITLE
aatams_biologging_snowpetrel -  New Harvester

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#301]
@xhoenner

**Comment by xhoenner** [comment]
succeeded on rc, @lbesnard can you test out https://github.com/aodn/geoserver-config/pull/281 before deploying this harvester to prod?

**Comment by xhoenner** [comment]
@danfruehauf it was deployed successfully on rc, could you deploy it to prod please?

**Comment by danfruehauf** [comment]
Yes, no worries.

**Comment by xhoenner** [comment]
Deployed on rc and prod, all good.
