### ISSUE TITLE
'bad version' warning during iHarvestResources

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#303]
In the log (console.2015-09-23-18-50-14.log) for anmn_ts_timeseries from last night (it had a big list of new files to harvest), there are many warnings like this:
```
...
* iHarvestResources modified/new resource file_id=5010
* iHarvestResources modified/new resource file_id=6427
Sep 24, 2015 2:50:53 AM ucar.nc2.iosp.hdf5.H5header$MessageAttribute read
SEVERE: bad version 72 at filePos 178346
Sep 24, 2015 2:50:53 AM ucar.nc2.iosp.hdf5.H5header$MessageAttribute read
SEVERE: bad version 72 at filePos 178346
* iHarvestResources modified/new resource file_id=7355
...
```
Overall the harvester seems to have run successfully, so maybe this is not a real issue.

**Comment by jonescc** [comment]
This ones come up before - ideally we'd upgrade the version of the netcdf library the harvesters are using to get rid of this error message.

Refer 

https://github.com/aodn/content/issues/83
https://github.com/Unidata/thredds/issues/50
https://github.com/nctoolbox/nctoolbox/issues/70

**Comment by mhidas** [comment]
@jonescc Thanks. I guess there's no point keeping it open here then.
