### ISSUE TITLE
AATAMS_SATTAG_DM failing due to missing tables in MS Access database files

### ISSUE THREAD

**Issue by xhoenner** [aodn/harvesters#307]
The current workflow for the AATAMS_SATTAG_DM data collection is handled entirely in Talend as follows:
1. A tSystem component downloads (using the LFTP mirroring function) into a 'zipped' folder all the .zip files that the tag manufacturer has uploaded into an imos directory on its FTP server.
2. A subjob then unzips all MS Access files and move them into another folder.
3. The harvester then queries different tables in each MS Access file using the tJDBC_input component and populate our PostgreSQL database using the data extracted by the query.

The issue is that sometimes the manufacturer uploads on its FTP directory .zip files for upcoming tag deployments. In this case, MS access files only have one table ('deployments') instead of ten, which creates errors in the tJDBC_input component when querying from a table that does not exist (for logs see https://github.com/aodn/content/issues/134, https://github.com/aodn/content/issues/139, https://github.com/aodn/content/issues/141).

After having investigated several options (*e.g.* bash script to remove erroneous MS Access files: https://github.com/aodn/harvesters/pull/305) @danfruehauf thinks that the best way to solve this issue would be to modify the tJDBC_input component to handle missing tables. @danfruehauf feel free to expand the description of this issue if I have missed something.

**Comment by danfruehauf** [comment]
Solved by #318
