### ISSUE TITLE
event-driven indexing fails when too many files uploaded at once

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#325]
We just got about a dozen files uploaded for the ANMN_AM pipeline (harvester anmn_am_dm). Most of them got checked, indexed and published fine, but one of them failed to index with this message:
```
Exception in component iUpdateIndex_1
org.postgresql.util.PSQLException: FATAL: too many connections for role "anmn_am_dm"
```
(The full log is at /mnt/ebs/log/data-services/ANMN_AM/IMOS_ANMN-AM_GST_20120417T060000Z_NRSMAI_FV01_NRSMAI-CO2-1204-delayed_END_20121018T220000Z_C-20151117T133603Z.nc.B5bN0o.20151119-114559.log)

**Comment by danfruehauf** [comment]
We'll need to see how we gonna throttle how many files can be indexed per facility at the same time. Not sure harvesters is the right place for it. For the time being, if that happens once every few 1000s of files, we can just move it back and let is reprocess.
