### ISSUE TITLE
ANMN_ACOUSTICS: new harvester

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#335]
Please deploy to RC, but do not schedule to run. This will only be run manually for now.

Merged in #332. Will need https://github.com/aodn/chef-private/pull/1692 to be merged for testing.

**Comment by lbesnard** [comment]
@mhidas I don't understand what you mean by 'do not schedule to run' . AFAIK it will run automatically,  maybe worth asking someone from the dev team

**Comment by ggalibert** [comment]
CMIIW but AFAIR any deployed harvester are automatically scheduled to run at least once a day or something.

The truth is IDK so IOW it's probably worth asking a developer. IYKWIM.

HTH and SCNR.

**Comment by mhidas** [comment]
All this harvester is doing (for now) is 
 * creating the schema with liquibase -- *this is really the only reason there is even a harvester for this collection*;
 * updating geometry column from lat/lon;
 * updating spatial extent in metadata record.

It is not actually harvesting anything (I update the content manually). That's why I suggested not running it every day, as it would be a bit pointless. But if it's actually more work to *not* run it, then fine, just let it run (or maybe do it just once a week).

Eventually we could get this harvester to update the content from a csv file, and make it event driven, but for something that gets updated 2-3 times a year, that's way more work than it's worth right now.

**Comment by lbesnard** [comment]
@ggalibert thanks for the good laugh

**Comment by atkinsn** [comment]
I laughed too... Thanks @ggalibert (I can github too...)

**Comment by mhidas** [comment]
@ggalibert @lbesnard Could you please deploy this harvester to RC? Doesn't matter if it's scheduled.

**Comment by ggalibert** [comment]
Deployed to RC

**Comment by mhidas** [comment]
Thanks @ggalibert . Tested and all good. Could you please deploy it to prod too?

**Comment by mhidas** [comment]
Thanks!
