### ISSUE TITLE
SRS - SST - reharvest of the files is not performed

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#337]
see
https://github.com/aodn/harvesters/pull/330#event-488739233
https://github.com/aodn/content/issues/149

A liquibase update was done to force the reprocess of SST files
```sql
UPDATE  file_harvest set last_moddate_harvested = '1970-01-03'
```

Unfortunately if didn't run on NSP14

Looking at the srs_sst.file_harvest table for example, the following line:
```sql
"19";"harvest";19;"1969-12-31 14:00:00+00";"readded";138
```
has likely been stuck since the last TPAC outage.

**Comment by lbesnard** [comment]
@jonescc

**Comment by jonescc** [comment]
@lbesnard - srs_sst is still running from 16th Dec.  It may yet get to this file and reprocess it.
