### ISSUE TITLE
Gridded data harvesters can be consolidated

### ISSUE THREAD

**Issue by danfruehauf** [aodn/harvesters#361]
Referring to the following harvesters (all gridded data):
- acorn_hourly_avg_nonqc
- acorn_hourly_avg_qc
- acorn_radial_nonqc
- acorn_radial_qc
- gsla_dm00
- gsla_nrt00
- srs_oc (Not sure??)
- srs_sst

All of those harvesters are populating a pretty simple schema by harvesting a timestamp from the netcdf file. By externalizing some configuration variables (such as the timestamp variable in the netcdf file) we can possibly build just one harvester for them all with different configurations.

SRS might be a little more annoying as it uses regular expression masking etc. But the solution for that can be a few incarnations of the srs_sst harvester. The regex masking proved already to be problematic in terms of performance.

Benefits:
- Less talend projects (and code)
- Untangling the srs_sst harvester

**Comment by jonescc** [comment]
Refer https://github.com/aodn/harvesters/pull/425 and https://github.com/aodn/talend-components/pull/54

Wondering if there is any other information we should be pulling out of the netcdf files  if we are going to rerun a generic harvester across our data collections (e.g. elevation), variable names, domain ranges etc

**Comment by jonescc** [comment]
Need to check with @julian1 re the type of metadata that was being pulled out of netcdf files by ncwms
