### ISSUE TITLE
SRS_OC harvester failing on liquibase

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#402]
New version of haverster to update views can't run because a drop on views is done and this affect the reporting schema ...

Any expert know what do to ? @julian1 @xhoenner 

```
liquibase.exception.DatabaseException: Error executing SQL DROP VIEW IF EXISTS srs_oc_so_johnson_chl_8d_aqua_url: ERROR: cannot drop view srs_oc_so_johnson_chl_8d_aqua_url because other objects depend on it
  Detail: view reporting.srs_all_deployments_view depends on view srs_oc_so_johnson_chl_8d_aqua_url
```

**Comment by pmbohm** [comment]
If this is still an issue it may be the cause of https://github.com/aodn/aodn-portal/issues/2236 @smancini
