### ISSUE TITLE
ANMN_NRS_LONG_TS deploy to prod

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#426]
Tested out ok in RC. Please deploy to prod!

**Comment by mhidas** [comment]
@lbesnard Would you mind? The Jenkins build should be ready. Just needs data bags.

**Comment by lbesnard** [comment]
@mhidas done here https://github.com/aodn/chef-private/pull/1962

Not in tomorrow tho

**Comment by mhidas** [comment]
@lbesnard Thanks!

**Comment by mhidas** [comment]
Ok, this is in prod. The data harvest works fine, though for now it's failing at the metadata update stage because the metadata record is not public yet.
