### ISSUE TITLE
ANMN_BURST_AVG_TIMESERIES should handle other non burst sampled biogeochem timeseries

### ISSUE THREAD

**Issue by ggalibert** [aodn/harvesters#473]
At the moment ANMN_BURST_AVG_TIMESERIES only harvest burst averaged data from WQMs and NXICs. However other instruments like ECOs collect biogeochem data (not in burst mode though) that is not picked up by the harvester.

Harvester should be updated in this regard and maybe should be renamed as well as its metadata record to something like ANMN_BIOGEOCHEM_TIMESERIES.

**Comment by ggalibert** [comment]
See for example those guys: http://thredds.aodn.org.au/thredds/catalog/IMOS/ANMN/QLD/PIL100/Biogeochem_timeseries/catalog.html

**Comment by mhidas** [comment]
Closing as this is now logged as a content issue (https://github.com/aodn/content/issues/398)
