### ISSUE TITLE
AODN RAN CTD - FUTURE REEF MAP

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#486]
@bpasquer , as we discussed about it, those harvester names should be renamed properly:

RAN_CTD_harvester to AODN_RAN_CTD_harvester
Future_Reef_MAP_harvester to FUTURE_REEF_MAP_harvester.

databags will have to be modified too

**Comment by bpasquer** [comment]
I keep that in mind for 2017 👍
