### ISSUE TITLE
anmn_nrs_ctd_profiles is missing CPHL column

### ISSUE THREAD

**Issue by ggalibert** [aodn/harvesters#491]
In this collection Chlorophyll data can be found under a parameter code CPHL. This needs to be added to the measurement table in the database and the view _data also needs to be updated.

**Comment by ggalibert** [comment]
See impact on Geoserver next : https://github.com/aodn/geoserver-config/issues/426

**Comment by mhidas** [comment]
This has been reported before: https://github.com/aodn/content/issues/209
