### ISSUE TITLE
AODN THREDDS catalog not validated by iIndexThreddsResources

### ISSUE THREAD

**Issue by bpasquer** [aodn/harvesters#494]
The AODN_RAN_CTD harvester used to harvest from the METOC THREDDS server that is now closed. The harvester has been updated to harvest the data from our THREDDS server. Tested on the PO BOX, the harvester raise an exception that suggests that either our catalog is not valid or the issue comes from the talend component iIndexThreddsResources or the librairies.  

aodn_ran_ctd.databasechangelog
INFO 1/18/17 12:59 PM:liquibase: Successfully released change log lock
Iterating over catalog at 'http://thredds.aodn.org.au/thredds/catalog/Department_of_Defence/RAN/CTD/catalog.xml'
Including only items matching these patterns: [.*nc]
Exception in component iIndexThreddsResources_2_iThredds
java.lang.Exception: Invalid catalog http://thredds.aodn.org.au/thredds/catalog/Department_of_Defence/RAN/CTD/catalog.xml
----Catalog Validation version 1.0.01
**Fatal:  InvCatalogFactory.readXML failed
 Exception= java.io.FileNotFoundException http://thredds.aodn.org.au/thredds/catalog/Department_of_Defence/RAN/CTD/catalog.xml
 fatalMessages= 
 errMessages= 
 warnMessages= 

	at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds$1.<init>(HarvestMetadataThredds.java:2548)
	at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.iIndexThreddsResources_2_iThreddsProcess(HarvestMetadataThredds.java:2493)
	at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.iPostgresqlDbUpdate_1Process(HarvestMetadataThredds.java:1338)
	at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.runJobInTOS(HarvestMetadataThredds.java:4676)
	at aodn_ran_ctd.harvestmetadatathredds_0_1.HarvestMetadataThredds.main(HarvestMetadataThredds.java:4446)
 catalog valid = false
[statistics] disconnected
Job HarvestMetadataThredds ended at 12:59 18/01/2017. [exit code=1]_

**Comment by jonescc** [comment]
Can you wget 'http://thredds.aodn.org.au/thredds/catalog/Department_of_Defence/RAN/CTD/catalog.xml' on your PO box?

**Comment by lbesnard** [comment]
no one can

**Comment by jonescc** [comment]
Well that's the reason why the harvester doesn't work.   Try thredds on the po box?

**Comment by lbesnard** [comment]
example, 
you can't do on the po box. but you can anywhere else
```
ncdump -h http://thredds.aodn.org.au/thredds/dodsC/IMOS/SOOP/SOOP-XBT/DELAYED/Line_IX22_Fremantle-Flores-Sea/2007/XBT_T_20071001T061200Z_IX22_FV01_ID-125795.nc
```
