### ISSUE TITLE
AODN_RAN_CTD harvester failing in RC and prod

### ISSUE THREAD

**Issue by bpasquer** [aodn/harvesters#501]
When manually triggered in RC and prod the AODN_RAN_CTD harvester( no pipeline for this collection) outputs the following error:

"_Exception in thread "main" java.lang.Error: java.lang.Error: java.lang.Error: java.lang.Error: java.lang.Error: java.lang.Error: java.lang.Error: java.lang.AbstractMethodError: org.slf4j.impl.JDK14LoggerAdapter.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)V
        at aodn_ran_ctd.aodn_ran_ctd_harvester_0_1.AODN_RAN_CTD_harvester.tRunJob_2Process(AODN_RAN_CTD_harvester.java:1199)
        at aodn_ran_ctd.aodn_ran_ctd_harvester_0_1.AODN_RAN_CTD_harvester.runJobInTOS(AODN_RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.aodn_ran_ctd_harvester_0_1.AODN_RAN_CTD_harvester.main(AODN_RAN_CTD_harvester.java:3070)_"

The harvester AODN_RAN_CTD cannot be tested on the PObox since it's harvesting from thredds server. But it ran successfully on my local machine.  Some help to understand the meaning of the error message would be very much appreciated.

**Comment by jonescc** [comment]
Has been rebuilt and promoted to rc.  Can this be tested there before promoting to RC?

**Comment by bpasquer** [comment]
yes, i've just triggered talend on RC

**Comment by bpasquer** [comment]
AODN_RAN_CTD harvester successfully ran on RC .

**Comment by bpasquer** [comment]
Can be promoted to prod. Thanks

**Comment by jonescc** [comment]
Promoted - will be deployed after 5pm this afternoon.
