### ISSUE TITLE
ABOS_TS harvester is not removing deleted files from collection

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#567]
Similar to many harvesters **ABOS_TS_SINGLE_INST_TIMESERIES** has a subjob called `DeleteTimeseriesFileData`, which is supposed to deal with deleted (or un-harvested) files by running the following SQL:
```sql
"delete from timeseries where file_id = '" + context.fileId + "'"
```
(where `context.fileId` is the file's id in the `indexed_file` table).  However, in this case this doesn't seem to be working, and the map view (and hence the portal collection) is full of files that should not be there:
```sql
harvest=> select count(*) from abos_ts.indexed_file  where not deleted ;                                               
 count 
-------
   290

harvest=> select count(distinct file_id)  from abos_ts.timeseries ;
 count 
-------
   544

harvest=> select count(*) from abos_ts.abos_ts_timeseries_map  ;
 count 
-------
   544
```
I have had a close look at the harvester, but have no idea what's causing this problem. Help!

**Comment by mhidas** [comment]
Maybe @jonescc could take a look at it?

**Comment by jonescc** [comment]
Looks to me like the problem files are all ones which were indexed before "2016-03-03 07:00:17.244+00" - perhaps related to moving to the pipeline or a bug which has since been fixed.

All files deleted after then appear to have been deleted correctly since then so perhaps just a cleanup of the problem files is required for the moment.

**Comment by mhidas** [comment]
Thanks @jonescc . I've had another look at these, and it turns out there's a bit more to the story (still in `abos_ts` schema):
```sql
select                                                                                          
  deleted as index_del,
  id not in (select file_id from timeseries) as meta_del,
  count(*),
  min(first_indexed) as first_indexed,
  max(last_indexed) as last_indexed
from indexed_file
group by index_del, meta_del
order by index_del, meta_del
;
 index_del | meta_del | count |         first_indexed         |        last_indexed        
-----------+----------+-------+-------------------------------+----------------------------
 f         | f        |   336 | 2016-04-27 23:19:31.961031+00 | 2017-12-05 02:34:22.901+00
 f         | t        |    41 | 2016-05-02 04:37:27.927254+00 | 2017-12-05 02:26:07.749+00
 t         | f        |   291 | 2014-03-04 17:00:36.54037+00  | 2016-03-03 07:00:17.244+00
 t         | t        |   495 | 2014-03-04 17:00:36.54037+00  | 2017-11-20 04:56:39.988+00
```
The files I mentioned before are in the third row (291 files). These files are actually **not deleted** i.e. they are still on S3 and indexed by the generic moorings harvest (`anmn_metadata`)

On the other hand, none of the 41 files in the second row exist on S3. So the index is wrong about these too, and some of them were updated as recently as two days ago.

The good news is that the content of the `timeseries` table, which is the basis of the portal layer, is more consistent with the files on S3, so maybe we can just ignore the `indexed_file.deleted` column?

**Comment by jonescc** [comment]
Looking at the logs for the 41 files on the second line above, the ones where logs are available were unable to be indexed and should have been moved to the error directory [error-files.txt](https://github.com/aodn/harvesters/files/1549566/error-files.txt)
.  Some are there, others aren't - can't find anymore detail about why they couldn't be indexed.

**Comment by jonescc** [comment]
PS.  The deleted flag is normally set when deleting a file from the index - I'd probably fix the flag rather than ignoring it.

**Comment by mhidas** [comment]
Thanks @jonescc . That makes sense now. Those 41 files that the index thinks are there were not harvested due to uniqueness constraints on the metadata table (`timeseries`).  I'm actually in the process of removing these constraints, so this will hopefully not happen in the future.

If/when we revisit the whole indexing/harvesting issue, depending on how far we want to go, we can:
* Update the index and do the rest of the harvest in a single db transaction, to keep them consistent (meaning files that fail to harvest would not be added to the index); or
* (_My preferred option_) Create a single, central index of all files we receive, which will then record what happened to the file, e.g. whether it passed the checker, got harvested successfully, and ended up on S3.

**Comment by mhidas** [comment]
In the meantime, yes we could get the index into a more consistent state by re-harvesting/un-harvesting the relevant files. However as data access via the portal is not affected by the delete flag in the index, I don't think this is worth the effort right now.
