### ISSUE TITLE
srs_surface_waves_map view not scalable when tables become large

### ISSUE THREAD

**Issue by lwgordonimos** [aodn/harvesters#656]
@ggalibert @lbesnard I suspect this is due to the view query not being scalable, and demonstrating acceptable performance for only very small tables.

I'd suggest we restore the prod schema onto RC and troubleshoot it there until it can be made to operate efficiently for very large tables, since if is choking already, it will only go downhill from here as the data continues to pour in.

The harvester appears to be getting stuck waiting for the following query to respond:
```sql
"select BoundingPolygonAsGml3('srs_surface_waves','srs_surface_waves_map','geom',1)"
```

This returns reasonably quickly on the RC schema with only 300 odd rows, but taking a very unreasonable amount of time in prod with 400,000.

**Comment by lwgordonimos** [comment]
It is being queried by that function though (which also calls other functions). 
e.g. https://github.com/aodn/harvest_sql_library/blob/master/extension/imos--1.0.sql#L303

That index is required to support the view anyway, since it uses the column in the join.

It may need over indexes as well, for example the geom column, but this would need to be testing/verified on RC.

**Comment by lbesnard** [comment]
https://github.com/aodn/harvesters/pull/657

**Comment by ggalibert** [comment]
I think we can close this one. Laurent has created a materialised view with index on geom which has improved performances significantly. 

Worth noting that the slow down on geom was being initiated by the talend component that updates the geospatial extent of the metadata record. We didn't really need this feature for this collection and took it off which also solved our performance problem when harvesting large number of files.
