### ISSUE TITLE
Complex SQL requests and best practices in harvesters

### ISSUE THREAD

**Issue by ggalibert** [aodn/harvesters#73]
To @lbesnard , @bpasquer , @xhoenner and maybe others.

I would like to attract your attention on complex SQL requests that sometimes require complex joints between tables. Most of the time I have seen that you mostly use nested SELECTs to achieve such operation while you can actually explicitly write which or which type of joint you may want to perform (like INNER JOIN or LEFT OUTER JOIN) between tables and this makes you a lot more aware of what's going to happen.

I'm not talking in terms of performance (this is not our problem ;-) ) but in terms of being less prone to a mistake, of ease of understanding and maintenance, nested queries are not ranking first. Our @julian1 expert might be able to confirm (or infirm!) this.

I will give an example. For SOOP_BA harvester I find the following SQL request :

```
SELECT vessel_name, platform_code,  colour 
FROM vessel_names 
WHERE (
   SELECT  vessel_name 
   FROM deployments 
   WHERE file_id = " + context.file_id +" 
) =  vessel_name
```

Not too complex, I can rapidly understand that we want to retrieve the content of the table vessel_names for the file_id = context.file_id, making a join with the table deployments on the common field vessel_name.

This is equivalent to the following SQL request :

```
SELECT vn.vessel_name, vn.platform_code, vn.colour 
FROM vessel_names vn 
   INNER JOIN deployments d 
      ON vn.vessel_name = d.vessel_name 
WHERE d.file_id = " + context.file_id +"
```

First you can see that I use aliases for the tables (vn for vessel_names) so that the fields mentioned in the select are explicitly the ones from the table I want (vn.vessel_name is the field vessel_name from the table vessel_names).

Second we clearly see that the request is articulated around the table vessel_names and that we are only going to retrieve some information when there is a match between vn.vessel_names and d.vessel_name (INNER JOIN ... ON ...). If an entry in the deployments table has its field vessel_name empty or not matching any vessel_name in the vessel_names table then we would retrieve nothing for this entry. 

However, this SQL request is part of a larger set of requests that are articulated around the table deployments (the WHERE d.file_id = " + context.file_id +" makes this actually obvious) and its field file_id, so we want to provide NULL results for this deployment regarding vessel_names otherwise this deployment entry will not be processed.

What we can do in order not to miss any deployment is this request :

```
SELECT vn.vessel_name, vn.platform_code, vn.colour 
FROM soop_ba.deployments d 
   LEFT OUTER JOIN vessel_names vn 
      ON vn.vessel_name = d.vessel_name 
WHERE d.file_id = " + context.file_id +"
```

This time we make it explicit that the request is articulated around the table deployments and it is also explicit that we want NULL results when there is not an exact joint with the table vessel_names since we use the LEFT OUTER JOIN vessel_names.

**Comment by xhoenner** [comment]
The content of this issue would be more appropriate in the Readme.md file, happy to do that @ggalibert?

**Comment by ggalibert** [comment]
Please see PR https://github.com/aodn/harvesters/pull/342

**Comment by mhidas** [comment]
@ggalibert Can this be closed?
