### ISSUE TITLE
auv harvester timestamp's different for tos7

### ISSUE THREAD

**Issue by jonescc** [aodn/harvesters#738]
refer https://github.com/aodn/utilities/pull/127

**Comment by jonescc** [comment]
Not sure how this impacts delivery through geoserver, but it creates a problem with csv export from the db as per the talend testing utility at the very least.

**Comment by lbesnard** [comment]
this should be fixed by this PR
https://github.com/aodn/harvesters/pull/751

**Comment by jonescc** [comment]
Resolved by https://github.com/aodn/harvesters/pull/751
