### ISSUE TITLE
anmn_nrs_dar_yon not updating map layer with removed files

### ISSUE THREAD

**Issue by jonescc** [aodn/harvesters#740]
Refer https://github.com/aodn/utilities/pull/148

**Comment by jonescc** [comment]
Also an issue with faimms

**Comment by lbesnard** [comment]
yeah those harvesters are a bit tricky as they are merging data together in various views. I would have to look at this again

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/harvesters/pull/752
