### ISSUE TITLE
Permission denied to replace view- Talend 7 run in Po Box7

### ISSUE THREAD

**Issue by bpasquer** [aodn/harvesters#781]
Running the ANFOG RT harvester after updating variable names in the _map and _data views output an error suggesting that the permission for the 'anfog_rt' role is not correctly set. Note that the issue impacts the views only as writing and updating table is allowed. 

> SEVERE 9/19/19 1:39 PM:liquibase: Change Set changelog.xml::cr-anfog_rt::bpasquer failed.  Error: Error executing SQL CREATE OR REPLACE VIEW anfog_rt_trajectory_data AS 
 	SELECT measurements.file_id,
 	b.deployment_name,
	b.platform_code,
	b.platform_type,
	b.dive_number,
	a.geospatial_vertical_max,
	a.geospatial_vertical_min,
[...]
	"VBSC_quality_control",
	measurements.geom
	FROM measurements
 	JOIN deployments a ON measurements.file_id = a.file_id
    JOIN deployment_id b ON measurements.file_id = b.file_id where status_filter in ('recovered', 'in_progress', 'aborted', 'potentially_lost', 'lost')
    ORDER BY measurements.file_id,measurements."TIME": ERROR: permission denied for schema anfog_rt

**Comment by bpasquer** [comment]
Whether I change the ChangeSet or not doesn't solve the issue. Any suggestions @jonescc ?

**Comment by jonescc** [comment]
Is this still a problem?  This is a database permission problem so would need to look at whether the user you are using to connect to the database has permission to create the view and if not why.  Most likely a chef database roles/permissions problem.

**Comment by jonescc** [comment]
Issue tracked to caching of database details by chef.  Owner of anfog_rt schema in db was postgres, but in the cached details it was anfog_rt and so no action was being taken by chef to fix the issue.

I had Bene delete the cached details /var/chef/cache/imos_postgresql/state/* and rerun the chef provisioning step and the ownership was fixed and the view could then be created.

**Comment by jonescc** [comment]
Raised https://github.com/aodn/chef/issues/882to look at caching issue.
